/**
 * GitHub ingest — fetch commits, classify meaningfulness, update repo + code signals.
 */

import { githubApi } from "@codexcap/connectors";
import { classifyCommit } from "@codexcap/core";
import {
  activitySignals,
  events,
  githubActivities,
  githubRepositories,
} from "@codexcap/db/schema";
import { and, desc, eq, gte, inArray } from "drizzle-orm";
import { db } from "@/lib/db";

export type GithubRefreshResult = {
  repositoryId: string;
  fullName: string;
  ok: boolean;
  commitsIngested: number;
  meaningfulFound: number;
  latestMeaningfulAt: string | null;
  error?: string;
};

export async function refreshGithubRepository(repositoryId: string): Promise<GithubRefreshResult> {
  const database = db();
  const [repo] = await database
    .select()
    .from(githubRepositories)
    .where(eq(githubRepositories.id, repositoryId))
    .limit(1);

  if (!repo) {
    return {
      repositoryId,
      fullName: "?",
      ok: false,
      commitsIngested: 0,
      meaningfulFound: 0,
      latestMeaningfulAt: null,
      error: "repository not found",
    };
  }

  const fullName = `${repo.owner}/${repo.repo}`;

  try {
    const meta = await githubApi.getRepository(repo.owner, repo.repo);
    if (!meta || meta.privateOrMissing) {
      await database
        .update(githubRepositories)
        .set({
          privateOrMissing: true,
          lastCheckedAt: new Date(),
          updatedAt: new Date(),
        })
        .where(eq(githubRepositories.id, repo.id));

      await database.insert(events).values({
        projectId: repo.projectId,
        eventType: "repo_private",
        title: `Repo unavailable: ${fullName}`,
        description: "GitHub returned private/missing for this repository",
        sourceUrl: repo.url,
        severity: "medium",
        autoGenerated: true,
        confirmed: true,
        dedupeKey: `repo-missing-${repo.id}-${new Date().toISOString().slice(0, 10)}`,
      }).onConflictDoNothing();

      return {
        repositoryId: repo.id,
        fullName,
        ok: false,
        commitsIngested: 0,
        meaningfulFound: 0,
        latestMeaningfulAt: null,
        error: "private or missing",
      };
    }

    const commits = await githubApi.listRecentCommits(repo.owner, repo.repo, {
      perPage: 30,
      hydrateMax: 15,
    });

    let ingested = 0;
    let meaningfulFound = 0;
    let latestMeaningfulAt: Date | null = null;
    let latestCommitAt: Date | null = null;

    for (const c of commits) {
      if (!latestCommitAt || c.committedAt > latestCommitAt) latestCommitAt = c.committedAt;

      const classified = classifyCommit({
        title: c.message,
        author: c.authorLogin ?? c.authorName,
        changedPaths: c.changedPaths,
        additions: c.additions,
        deletions: c.deletions,
      });

      if (classified.isMeaningful) {
        meaningfulFound += 1;
        if (!latestMeaningfulAt || c.committedAt > latestMeaningfulAt) {
          latestMeaningfulAt = c.committedAt;
        }
      }

      const existing = await database
        .select({ id: githubActivities.id, humanOverride: githubActivities.humanOverride })
        .from(githubActivities)
        .where(
          and(eq(githubActivities.repositoryId, repo.id), eq(githubActivities.commitSha, c.sha)),
        )
        .limit(1);

      if (existing[0]?.humanOverride) {
        continue;
      }

      if (existing[0]) {
        await database
          .update(githubActivities)
          .set({
            timestamp: c.committedAt,
            author: c.authorLogin ?? c.authorName,
            title: c.message,
            filesChanged: c.changedPaths.length || null,
            additions: c.additions,
            deletions: c.deletions,
            changedPaths: c.changedPaths,
            classification: classified.classification,
            meaningfulScore: classified.meaningfulScore,
            classificationReason: classified.reason,
            sourceUrl: c.htmlUrl,
            updatedAt: new Date(),
          })
          .where(eq(githubActivities.id, existing[0].id));
      } else {
        await database.insert(githubActivities).values({
          repositoryId: repo.id,
          commitSha: c.sha,
          timestamp: c.committedAt,
          author: c.authorLogin ?? c.authorName,
          title: c.message,
          filesChanged: c.changedPaths.length || null,
          additions: c.additions,
          deletions: c.deletions,
          changedPaths: c.changedPaths,
          classification: classified.classification,
          meaningfulScore: classified.meaningfulScore,
          classificationReason: classified.reason,
          sourceUrl: c.htmlUrl,
        });
        ingested += 1;

        if (classified.isMeaningful) {
          await database
            .insert(events)
            .values({
              projectId: repo.projectId,
              eventType: "meaningful_commit",
              timestamp: c.committedAt,
              title: `Meaningful commit on ${fullName}`,
              description: `${c.message} · score ${classified.meaningfulScore}/10 · ${classified.classification}`,
              sourceUrl: c.htmlUrl,
              severity: "info",
              autoGenerated: true,
              confirmed: true,
              dedupeKey: `meaningful-${repo.id}-${c.sha}`,
              metadata: {
                sha: c.sha,
                score: classified.meaningfulScore,
                classification: classified.classification,
              },
            })
            .onConflictDoNothing();
        }
      }
    }

    // If we didn't hydrate meaningful from this batch, keep prior DB max
    if (!latestMeaningfulAt) {
      const [prior] = await database
        .select({ timestamp: githubActivities.timestamp })
        .from(githubActivities)
        .where(
          and(
            eq(githubActivities.repositoryId, repo.id),
            gte(githubActivities.meaningfulScore, 5),
          ),
        )
        .orderBy(desc(githubActivities.timestamp))
        .limit(1);
      latestMeaningfulAt = prior?.timestamp ?? null;
    }

    await database
      .update(githubRepositories)
      .set({
        defaultBranch: meta.defaultBranch,
        stars: meta.stars,
        forks: meta.forks,
        openIssues: meta.openIssues,
        archived: meta.archived,
        privateOrMissing: false,
        latestCommitAt: latestCommitAt ?? meta.latestCommitAt,
        latestMeaningfulCommitAt: latestMeaningfulAt,
        lastCheckedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(githubRepositories.id, repo.id));

    await refreshProjectCodeSignal(repo.projectId);

    return {
      repositoryId: repo.id,
      fullName,
      ok: true,
      commitsIngested: ingested,
      meaningfulFound,
      latestMeaningfulAt: latestMeaningfulAt?.toISOString() ?? null,
    };
  } catch (e) {
    return {
      repositoryId: repo.id,
      fullName,
      ok: false,
      commitsIngested: 0,
      meaningfulFound: 0,
      latestMeaningfulAt: null,
      error: e instanceof Error ? e.message : "github refresh failed",
    };
  }
}

async function refreshProjectCodeSignal(projectId: string) {
  const database = db();
  const repos = await database
    .select()
    .from(githubRepositories)
    .where(eq(githubRepositories.projectId, projectId));

  const latestMeaningful = repos
    .map((r) => r.latestMeaningfulCommitAt)
    .filter((d): d is Date => !!d)
    .sort((a, b) => b.getTime() - a.getTime())[0];

  const latestAny = repos
    .map((r) => r.latestCommitAt)
    .filter((d): d is Date => !!d)
    .sort((a, b) => b.getTime() - a.getTime())[0];

  const since7 = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const since30 = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  const repoIds = repos.map((r) => r.id);

  let meaningful7 = 0;
  let meaningful30 = 0;
  let total7 = 0;
  let total30 = 0;
  let filesChanged30: number | null = null;
  let additions30: number | null = null;
  let deletions30: number | null = null;

  if (repoIds.length) {
    const acts = await database
      .select({
        timestamp: githubActivities.timestamp,
        meaningfulScore: githubActivities.meaningfulScore,
        filesChanged: githubActivities.filesChanged,
        additions: githubActivities.additions,
        deletions: githubActivities.deletions,
      })
      .from(githubActivities)
      .where(inArray(githubActivities.repositoryId, repoIds));

    const in7 = acts.filter((a) => a.timestamp >= since7);
    const in30 = acts.filter((a) => a.timestamp >= since30);
    total7 = in7.length;
    total30 = in30.length;
    meaningful7 = in7.filter((a) => (a.meaningfulScore ?? 0) >= 5).length;
    meaningful30 = in30.filter((a) => (a.meaningfulScore ?? 0) >= 5).length;

    const churnKnown = in30.filter(
      (a) => a.filesChanged != null || a.additions != null || a.deletions != null,
    );
    if (churnKnown.length) {
      filesChanged30 = churnKnown.reduce((s, a) => s + (a.filesChanged ?? 0), 0);
      additions30 = churnKnown.reduce((s, a) => s + (a.additions ?? 0), 0);
      deletions30 = churnKnown.reduce((s, a) => s + (a.deletions ?? 0), 0);
    }
  }

  const days =
    latestMeaningful != null
      ? Math.floor((Date.now() - latestMeaningful.getTime()) / (1000 * 60 * 60 * 24))
      : null;

  const summary = latestMeaningful
    ? `Meaningful code ${latestMeaningful.toISOString().slice(0, 10)} · ${meaningful7} in 7d · ${meaningful30} in 30d`
    : latestAny
      ? `Commits seen but none classified meaningful yet · last ${latestAny.toISOString().slice(0, 10)}`
      : "No GitHub activity ingested yet";

  const metrics = {
    meaningful7,
    meaningful30,
    total7,
    total30,
    daysSinceMeaningful: days,
    filesChanged30,
    additions30,
    deletions30,
  };

  const existing = await database
    .select()
    .from(activitySignals)
    .where(and(eq(activitySignals.projectId, projectId), eq(activitySignals.signalType, "code")))
    .limit(1);

  const values = {
    latestAt: latestMeaningful ?? latestAny ?? null,
    source: "github_api",
    confidence: latestMeaningful ? 8 : latestAny ? 4 : 2,
    summary,
    metrics,
    updatedAt: new Date(),
  };

  if (existing[0]) {
    await database.update(activitySignals).set(values).where(eq(activitySignals.id, existing[0].id));
  } else {
    await database.insert(activitySignals).values({
      projectId,
      signalType: "code",
      ...values,
    });
  }
}

export async function refreshProjectGithub(projectId: string): Promise<GithubRefreshResult[]> {
  const repos = await db()
    .select()
    .from(githubRepositories)
    .where(eq(githubRepositories.projectId, projectId));
  const results: GithubRefreshResult[] = [];
  for (const r of repos) {
    results.push(await refreshGithubRepository(r.id));
  }
  return results;
}

export async function refreshAllGithub(): Promise<GithubRefreshResult[]> {
  const repos = await db().select().from(githubRepositories);
  const results: GithubRefreshResult[] = [];
  for (const r of repos) {
    results.push(await refreshGithubRepository(r.id));
    await new Promise((res) => setTimeout(res, 200));
  }
  return results;
}

export async function recentActivitiesForRepos(repositoryIds: string[], limit = 40) {
  if (!repositoryIds.length) return [];
  return db()
    .select()
    .from(githubActivities)
    .where(inArray(githubActivities.repositoryId, repositoryIds))
    .orderBy(desc(githubActivities.timestamp))
    .limit(limit);
}

const NOISE_CLASSES = new Set([
  "documentation",
  "dependency_update",
  "formatting",
  "generated",
  "readme_only",
]);

export async function projectGithubStats(projectId: string) {
  const repos = await db()
    .select()
    .from(githubRepositories)
    .where(eq(githubRepositories.projectId, projectId));
  const repoIds = repos.map((r) => r.id);
  const since7 = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const since30 = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

  let meaningful7 = 0;
  let meaningful30 = 0;
  let total7 = 0;
  let total30 = 0;
  let filesChanged30: number | null = null;
  let additions30: number | null = null;
  let deletions30: number | null = null;
  let noise30 = 0;
  let activities: (typeof githubActivities.$inferSelect)[] = [];
  let allScored: (typeof githubActivities.$inferSelect)[] = [];

  if (repoIds.length) {
    allScored = await db()
      .select()
      .from(githubActivities)
      .where(inArray(githubActivities.repositoryId, repoIds))
      .orderBy(desc(githubActivities.timestamp));

    activities = allScored.slice(0, 80);

    const in7 = allScored.filter((a) => a.timestamp >= since7);
    const in30 = allScored.filter((a) => a.timestamp >= since30);
    total7 = in7.length;
    total30 = in30.length;
    meaningful7 = in7.filter((a) => (a.meaningfulScore ?? 0) >= 5).length;
    meaningful30 = in30.filter((a) => (a.meaningfulScore ?? 0) >= 5).length;
    noise30 = in30.filter(
      (a) =>
        (a.meaningfulScore ?? 0) < 5 ||
        NOISE_CLASSES.has((a.classification ?? "").toLowerCase()),
    ).length;

    const churnKnown = in30.filter(
      (a) => a.filesChanged != null || a.additions != null || a.deletions != null,
    );
    if (churnKnown.length) {
      filesChanged30 = churnKnown.reduce((s, a) => s + (a.filesChanged ?? 0), 0);
      additions30 = churnKnown.reduce((s, a) => s + (a.additions ?? 0), 0);
      deletions30 = churnKnown.reduce((s, a) => s + (a.deletions ?? 0), 0);
    }
  }

  const latestMeaningful = repos
    .map((r) => r.latestMeaningfulCommitAt)
    .filter((d): d is Date => !!d)
    .sort((a, b) => b.getTime() - a.getTime())[0];

  const latestCommit = repos
    .map((r) => r.latestCommitAt)
    .filter((d): d is Date => !!d)
    .sort((a, b) => b.getTime() - a.getTime())[0];

  const daysSinceMeaningful =
    latestMeaningful != null
      ? Math.floor((Date.now() - latestMeaningful.getTime()) / (1000 * 60 * 60 * 24))
      : null;

  const recentMeaningful = allScored
    .filter((a) => (a.meaningfulScore ?? 0) >= 5)
    .slice(0, 8);

  const noiseExcluded = allScored
    .filter(
      (a) =>
        (a.meaningfulScore ?? 0) < 5 &&
        NOISE_CLASSES.has((a.classification ?? "").toLowerCase()),
    )
    .slice(0, 12);

  const noiseSummary: Record<string, number> = {};
  for (const a of allScored.filter((x) => x.timestamp >= since30)) {
    if ((a.meaningfulScore ?? 0) >= 5) continue;
    const key = (a.classification ?? "unknown").replace(/_/g, " ");
    noiseSummary[key] = (noiseSummary[key] ?? 0) + 1;
  }

  return {
    repos,
    activities,
    meaningful7,
    meaningful30,
    total7,
    total30,
    filesChanged30,
    additions30,
    deletions30,
    noise30,
    daysSinceMeaningful,
    latestMeaningful,
    latestCommit,
    recentMeaningful,
    noiseExcluded,
    noiseSummary,
  };
}
